//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PZ.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messages
    {
        public int MessageID { get; set; }
        public string Content { get; set; }
        public System.DateTime Time { get; set; }
        public Nullable<int> ConversationID_ConversationID { get; set; }
        public Nullable<int> UserID_UserID { get; set; }
    
        public virtual Conversations Conversations { get; set; }
        public virtual Users Users { get; set; }
    }
}
